// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float4 res = Result[id.xy];

    int red = res.r * 10000000;
    int blue = res.b * 10000000;
    int green = res.g * 10000000;

    Result[id.xy] = float4(red / 10000000.0, green / 10000000.0, blue / 100000000.0, 1);
}
